export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const IS_FETCHING_USER = 'IS_FETCHING_USER';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
